# -*- coding: utf-8 -*-
"""Data_PI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5Vk6xuBk9gDTScjSQNk9ZojJEa76MQn

# Implementasi PI

### Import Library yang dibutuhkan
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pickle
import random
from scipy import stats

# Set seed agar hasil acak tetap konsisten setiap kali script dijalankan
np.random.seed(42)
RANDOM_SEED = 42

"""# 1. DATA PREPARATION

### 1.1 PREPROCESSING DATA ITEM (MENU)
"""

print("Memproses Data Menu (nutrition.csv)...")
df_nutrition = pd.read_csv('nutrition.csv')

# Ambil 150 baris pertama sebagai sampel
df_menu = df_nutrition.head(150).copy()

# Buang kolom yang tidak relevan dan ubah nama kolom
df_menu = df_menu[['id', 'name']]
df_menu.rename(columns={'id': 'ID_Menu', 'name': 'Nama_Menu'}, inplace=True)

# Definisikan batasan karakteristik menu
kategori = ['Makanan Utama', 'Camilan', 'Minuman']
bahan_baku = ['Nasi', 'Mie', 'Ayam', 'Daging', 'Kopi', 'Cokelat', 'Teh', 'Sayuran']
rasa = ['Manis', 'Gurih', 'Pedas']

# Injeksi fitur Content-Based secara acak
df_menu['Kategori_Hidangan'] = np.random.choice(kategori, len(df_menu))
df_menu['Bahan_Baku'] = np.random.choice(bahan_baku, len(df_menu))
df_menu['Rasa_Dominan'] = np.random.choice(rasa, len(df_menu))

# Simpan dataset Item
df_menu.to_csv('data_menu_final.csv', index=False)
print("-> data_menu_final.csv berhasil dibuat dengan", len(df_menu), "baris.\n")

"""### 1.2 PREPROCESSING DATA TRANSAKSI"""

print("Memproses Data Transaksi (synthetic_fooddelivery_dataset_CLEANED.csv)...")
df_delivery = pd.read_csv('synthetic_fooddelivery_dataset_CLEANED.csv')

# Buat 500 ID Pelanggan (User_ID) untuk Collaborative Filtering
daftar_user_id = [f"U{str(i).zfill(3)}" for i in range(1, 501)]

# Injeksi User_ID ke seluruh 8500 baris transaksi
df_delivery['User_ID'] = np.random.choice(daftar_user_id, len(df_delivery))

# Injeksi ID_Menu dari df_menu yang sudah dibuat sebelumnya
daftar_id_menu = df_menu['ID_Menu'].tolist()
df_delivery['ID_Menu'] = np.random.choice(daftar_id_menu, len(df_delivery))

# Filter kolom yang hanya digunakan untuk sistem rekomendasi
kolom_relevan = ['User_ID', 'ID_Menu', 'Rating_Pelanggan', 'Waktu_Transaksi']
df_transaksi = df_delivery[kolom_relevan].copy()

# Mengatasi kemungkinan nilai NaN pada Rating (jika ada) dengan nilai rata-rata
df_transaksi['Rating_Pelanggan'] = df_transaksi['Rating_Pelanggan'].fillna(df_transaksi['Rating_Pelanggan'].mean())

# Simpan dataset Transaksi
df_transaksi.to_csv('data_transaksi_final.csv', index=False)
print("-> data_transaksi_final.csv berhasil dibuat dengan", len(df_transaksi), "baris.")

"""# 2. Membuat Modul Content-Based Filtering"""

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)

"""### 2.1 Memuat Data yang sudah dipreprocessing tadi"""

df_menu = pd.read_csv('data_menu_final.csv')

print("=== 1. Muat Data Menu ===")
print(f"Jumlah menu: {df_menu.shape[0]} baris, {df_menu.shape[1]} kolom")
print(df_menu.head(5))
print()

# Validasi cepat: pastikan tidak ada nilai kosong di kolom fitur utama
kolom_fitur = ['Kategori_Hidangan', 'Bahan_Baku', 'Rasa_Dominan']
missing = df_menu[kolom_fitur].isna().sum()
if missing.sum() > 0:
    print("PERINGATAN - ada nilai kosong pada kolom fitur:")
    print(missing[missing > 0])
else:
    print("Tidak ada nilai kosong pada kolom fitur (Kategori/Bahan/Rasa). Aman lanjut.")
print()

"""### 2.2 EKSTRAKSI FITUR (FEATURE ENCODING) -> TF-IDF"""

def buat_fitur_gabungan(row):
    kategori = str(row['Kategori_Hidangan']).replace(' ', '_')
    bahan = str(row['Bahan_Baku']).replace(' ', '_')
    rasa = str(row['Rasa_Dominan']).replace(' ', '_')
    return f"{kategori} {bahan} {rasa}"

df_menu['fitur_gabungan'] = df_menu.apply(buat_fitur_gabungan, axis=1)

print("=== 2. Ekstraksi Fitur (Feature Encoding) ===")
print("Contoh representasi string gabungan per menu:")
print(df_menu[['Nama_Menu', 'fitur_gabungan']].head(6).to_string(index=False))
print()

tfidf = TfidfVectorizer(token_pattern=r'(?u)\b\w+\b')
tfidf_matrix = tfidf.fit_transform(df_menu['fitur_gabungan'])

print(f"Ukuran matriks TF-IDF: {tfidf_matrix.shape} "
      f"({tfidf_matrix.shape[0]} menu x {tfidf_matrix.shape[1]} fitur unik)")
print(f"Vocabulary (fitur unik hasil encoding): {list(tfidf.get_feature_names_out())}")
print()

"""### 2.3  HITUNG COSINE SIMILARITY"""

cos_sim = cosine_similarity(tfidf_matrix)

print("=== 3. Hitung Cosine Similarity ===")
print(f"Ukuran matriks kemiripan: {cos_sim.shape} (matriks menu x menu, simetris)")
print()

"""### 2.4 FUNGSI BANTU: AMBIL TOP-N MENU PALING MIRIP"""

def get_menu_serupa(nama_menu, top_n=5):
    """
    Mengembalikan top-N menu paling mirip dengan `nama_menu` berdasarkan
    skor cosine similarity dari fitur Kategori/Bahan/Rasa.
    Item itu sendiri selalu dikeluarkan dari hasil.
    """
    cocok = df_menu.index[df_menu['Nama_Menu'].str.lower() == nama_menu.lower()]
    if len(cocok) == 0:
        print(f"Menu '{nama_menu}' tidak ditemukan di data_menu_final.csv")
        return pd.DataFrame()

    idx = cocok[0]
    skor = [(i, s) for i, s in enumerate(cos_sim[idx]) if i != idx]
    skor = sorted(skor, key=lambda x: x[1], reverse=True)[:top_n]

    hasil = df_menu.iloc[[i for i, _ in skor]][
        ['Nama_Menu', 'Kategori_Hidangan', 'Bahan_Baku', 'Rasa_Dominan']
    ].copy()
    hasil['skor_kemiripan'] = [round(s, 3) for _, s in skor]
    return hasil.reset_index(drop=True)


print("=== 4. Contoh Pengujian: menu paling mirip ===")
contoh = df_menu['Nama_Menu'].iloc[10]
print(f"Menu paling mirip dengan '{contoh}':")
print(get_menu_serupa(contoh, top_n=5).to_string(index=False))
print()

"""### 2.5 REKOMENDASI DARI PREFERENSI LANGSUNG (untuk cold start)"""

def rekomendasi_dari_preferensi(kategori=None, bahan=None, rasa=None, top_n=5):
    """
    Merekomendasikan menu berdasarkan preferensi yang dinyatakan langsung
    oleh pelanggan baru (bukan dari riwayat transaksi). Parameter yang
    tidak diisi (None) diabaikan.
    """
    bagian = []
    if kategori:
        bagian.append(str(kategori).replace(' ', '_'))
    if bahan:
        bagian.append(str(bahan).replace(' ', '_'))
    if rasa:
        bagian.append(str(rasa).replace(' ', '_'))

    if not bagian:
        print("Isi minimal satu preferensi (kategori/bahan/rasa).")
        return pd.DataFrame()

    query_vec = tfidf.transform([' '.join(bagian)])
    skor = cosine_similarity(query_vec, tfidf_matrix).flatten()

    hasil = df_menu.copy()
    hasil['skor_kecocokan'] = skor.round(3)
    hasil = hasil.sort_values('skor_kecocokan', ascending=False).head(top_n)
    return hasil[['Nama_Menu', 'Kategori_Hidangan', 'Bahan_Baku',
                   'Rasa_Dominan', 'skor_kecocokan']].reset_index(drop=True)


print("=== 4b. Contoh Pengujian: cold start (pelanggan baru, tanpa riwayat) ===")
print("Preferensi: suka rasa Pedas, bahan Ayam")
print(rekomendasi_dari_preferensi(bahan='Ayam', rasa='Pedas', top_n=5).to_string(index=False))
print()

"""### 2.6 SIMPAN ARTEFAK UNTUK TAHAP COLLABORATIVE FILTERING DAN HYBRID FILTERING"""

with open('cbf_artifacts.pkl', 'wb') as f:
    pickle.dump({
        'df_menu': df_menu,
        'tfidf_vectorizer': tfidf,
        'tfidf_matrix': tfidf_matrix,
        'cosine_sim_matrix': cos_sim,
    }, f)

print("Artefak CBF (df_menu, tfidf_vectorizer, tfidf_matrix, cosine_sim_matrix)")
print("disimpan ke 'cbf_artifacts.pkl' -- siap dipakai di Tahap 2 (Collaborative")
print("Filtering) dan Tahap 3 (penggabungan Hybrid).")

"""# 3. MEMBUAT MODUL COLLABORATIVE FILTERING

Modul ini merekomendasikan menu berdasarkan KEMIRIPAN POLA RIWAYAT
TRANSAKSI ANTAR PELANGGAN (User-to-User), bukan dari fitur menu itu
sendiri seperti di Tahap 1 (CBF). Inilah komponen CF pada Hybrid
Filtering, yang justru BUTUH riwayat transaksi sehingga secara
prinsip tidak bisa dipakai untuk pelanggan baru (cold start). Itu
sebabnya CF selalu perlu didampingi CBF (Tahap 1) di dalam Hybrid
Filtering.

### 3.1 MEMUAT DATA
"""

df_trans = pd.read_csv('data_transaksi_final.csv')

print("=== 1. Muat Data Transaksi ===")
print(f"Jumlah baris transaksi: {df_trans.shape[0]}")
print(f"Jumlah pelanggan (User_ID) unik: {df_trans['User_ID'].nunique()}")
print(f"Jumlah menu yang pernah ditransaksikan: {df_trans['ID_Menu'].nunique()}")
print(df_trans.head())
print()

# Beberapa pelanggan memesan menu yang sama lebih dari sekali (rating beda-beda
# di waktu berbeda). Sebelum dibuat pivot table, ini diagregasi dulu dengan
# rata-rata rating per pasangan (User_ID, ID_Menu), supaya pivot table valid
# (pivot_table butuh 1 nilai unik per sel baris x kolom).
n_duplikat = df_trans.duplicated(subset=['User_ID', 'ID_Menu']).sum()
print(f"Pasangan (User_ID, ID_Menu) yang muncul >1 kali: {n_duplikat}")
df_agg = (df_trans
          .groupby(['User_ID', 'ID_Menu'], as_index=False)['Rating_Pelanggan']
          .mean())
print(f"Baris setelah agregasi (rata-rata rating per user-menu): {len(df_agg)}")
print()

"""### 3.2 BUAT USER-ITEM MATRIX (PIVOT TABLE)"""

user_item_matrix = df_agg.pivot_table(
    index='User_ID', columns='ID_Menu', values='Rating_Pelanggan'
)

n_user, n_item = user_item_matrix.shape
terisi = df_agg.shape[0]
sparsity = 100 * (1 - terisi / (n_user * n_item))

print("=== 2. User-Item Matrix ===")
print(f"Ukuran matriks: {n_user} user x {n_item} menu")
print(f"Sparsity (persentase sel kosong / belum pernah dipesan): {sparsity:.2f}%")
print("Cuplikan matriks (sel kosong = pelanggan belum pernah pesan menu itu):")
print(user_item_matrix.iloc[:5, :8])
print()

"""### 3.3 HITUNG USER-USER SIMILARITY"""

# Dipakai ADJUSTED COSINE SIMILARITY: setiap rating dikurangi rata-rata
# rating pelanggan itu sendiri (mean-centering) sebelum dihitung cosine similarity.

user_means = user_item_matrix.mean(axis=1)
uim_centered = user_item_matrix.sub(user_means, axis=0).fillna(0)

user_sim = cosine_similarity(uim_centered)
user_sim_df = pd.DataFrame(
    user_sim, index=user_item_matrix.index, columns=user_item_matrix.index
)

print("=== 3. User-User Similarity ===")
print(f"Ukuran matriks kemiripan antar-user: {user_sim_df.shape}")
contoh_user = user_item_matrix.index[0]
top_mirip = user_sim_df[contoh_user].drop(contoh_user).sort_values(ascending=False).head(5)
print(f"\n5 pelanggan paling mirip dengan {contoh_user}:")
print(top_mirip.to_string())
print()

"""### 3.4 PREDIKSI SKOR (User-Based CF)"""

def prediksi_rating(user_id, item_id, k=10):
    """
    Memprediksi skor (rating) yang kemungkinan akan diberikan `user_id`
    untuk `item_id`, berdasarkan rating item tersebut dari k pelanggan
    lain yang paling mirip (dan sudah pernah menilai item ini).

    Rumus: pred(u,i) = mean(u) + [ sum_v sim(u,v) * (r(v,i) - mean(v)) ]
                                   / sum_v |sim(u,v)|
    untuk v = tetangga (user lain) yang sudah menilai item i.
    """
    if user_id not in user_item_matrix.index or item_id not in user_item_matrix.columns:
        return None

    # user lain yang sudah pernah menilai item ini
    penilai = user_item_matrix[item_id].dropna().drop(index=user_id, errors='ignore')
    if len(penilai) == 0:
        return None  # tidak ada satu pun tetangga yang pernah menilai item ini

    sim_ke_penilai = user_sim_df.loc[user_id, penilai.index]
    sim_ke_penilai = sim_ke_penilai[sim_ke_penilai > 0]  # hanya tetangga yang "searah"
    if len(sim_ke_penilai) == 0:
        return None

    top_k = sim_ke_penilai.sort_values(ascending=False).head(k)
    pembilang = sum(
        top_k[v] * (user_item_matrix.loc[v, item_id] - user_means[v])
        for v in top_k.index
    )
    penyebut = sum(abs(s) for s in top_k)
    if penyebut == 0:
        return None
    return user_means[user_id] + pembilang / penyebut

"""### 3.5 FUNGSI REKOMENDASI TOP-N (CF)"""

def rekomendasi_cf(user_id, top_n=5, k=10):
    """
    Mengembalikan top-N menu dengan prediksi skor tertinggi untuk
    `user_id`, dari menu-menu yang BELUM pernah dia pesan.
    Mengembalikan None kalau user_id tidak dikenali sama sekali
    (khas kasus pelanggan baru/cold start -- CF tidak bisa menangani ini,
    harus dilempar ke CBF di Tahap 1).
    """
    if user_id not in user_item_matrix.index:
        print(f"[Cold Start] {user_id} tidak ada riwayat transaksi -- "
              "CF tidak bisa memprediksi apa pun. Gunakan CBF (Tahap 1).")
        return pd.DataFrame()

    sudah_dipesan = user_item_matrix.loc[user_id].dropna().index
    kandidat = [i for i in user_item_matrix.columns if i not in sudah_dipesan]

    hasil = []
    for item in kandidat:
        pred = prediksi_rating(user_id, item, k=k)
        if pred is not None:
            hasil.append((item, pred))

    hasil.sort(key=lambda x: x[1], reverse=True)
    hasil = hasil[:top_n]

    if not hasil:
        return pd.DataFrame()

    df_hasil = df_menu[df_menu['ID_Menu'].isin([i for i, _ in hasil])].copy()
    skor_map = dict(hasil)
    df_hasil['skor_prediksi'] = df_hasil['ID_Menu'].map(skor_map).round(2)
    df_hasil = df_hasil.sort_values('skor_prediksi', ascending=False)
    return df_hasil[['Nama_Menu', 'Kategori_Hidangan', 'Bahan_Baku',
                      'Rasa_Dominan', 'skor_prediksi']].reset_index(drop=True)


print("=== 4 & 5. Contoh Pengujian: Prediksi & Rekomendasi CF ===")
contoh_user = 'U001'
print(f"Top-5 rekomendasi CF untuk pelanggan lama {contoh_user}:")
print(rekomendasi_cf(contoh_user, top_n=5).to_string(index=False))
print()

print("Contoh kasus cold start (User_ID tidak ada di data transaksi):")
rekomendasi_cf('U999_BARU', top_n=5)
print()

"""### 3.6 SIMPAN ARTEFAK UNTUK TAHAP HYBRID"""

with open('cf_artifacts.pkl', 'wb') as f:
    pickle.dump({
        'user_item_matrix': user_item_matrix,
        'user_means': user_means,
        'user_similarity_matrix': user_sim_df,
    }, f)

print("Artefak CF (user_item_matrix, user_means, user_similarity_matrix)")
print("disimpan ke 'cf_artifacts.pkl' -- siap digabung dengan hasil CBF")
print("(cbf_artifacts.pkl) di Tahap 3 untuk membentuk Hybrid Filtering.")

"""# 4. Arsitektur Switching & Weighted Hybrid (Skenario Cold Start)

Menggabungkan Content-Based Filtering dan Collaborative Filtering jadi satu sistem hybrid.

### 4.1 MUAT ARTEFAK Content-Based Filtering & Collaborative Filtering
"""

with open('cbf_artifacts.pkl', 'rb') as f:
    cbf = pickle.load(f)
with open('cf_artifacts.pkl', 'rb') as f:
    cf = pickle.load(f)

df_menu = cbf['df_menu']
tfidf = cbf['tfidf_vectorizer']
tfidf_matrix = cbf['tfidf_matrix']
cos_sim = cbf['cosine_sim_matrix']

user_item_matrix = cf['user_item_matrix']
user_means = cf['user_means']
user_sim_df = cf['user_similarity_matrix']

# map ID_Menu -> posisi baris di df_menu / cos_sim, dipakai berkali-kali
id_to_idx = {mid: i for i, mid in enumerate(df_menu['ID_Menu'])}

print("=== 1. Artefak Tahap Content-Based Filtering & Tahap Collaborative Filtering berhasil dimuat ===")
print(f"CBF: {cos_sim.shape[0]} menu | CF: {user_item_matrix.shape[0]} pelanggan lama")
print()

"""### 4.2 SKOR CBF-AFFINITY (profil rasa pelanggan LAMA dari riwayatnya)"""

def cbf_affinity(user_id, candidate_item_id):
    """
    Seberapa cocok `candidate_item_id` dengan "selera" pelanggan lama,
    dihitung dari kemiripan konten (CBF) ke SEMUA menu yang pernah ia
    nilai, dibobot oleh rating yang ia beri (menu yang dinilai tinggi
    berpengaruh lebih besar ke profil selera dibanding yang dinilai
    rendah). Hasilnya tetap di rentang skor kemiripan 0-1.
    """
    riwayat = user_item_matrix.loc[user_id].dropna()
    if len(riwayat) == 0:
        return 0.0
    cand_idx = id_to_idx[candidate_item_id]
    total_skor = sum(rating * cos_sim[cand_idx, id_to_idx[item_id]]
                      for item_id, rating in riwayat.items())
    total_bobot = riwayat.sum()
    return total_skor / total_bobot if total_bobot > 0 else 0.0

"""### 4.3 WEIGHTED HYBRID (untuk pelanggan LAMA): gabung skor CF + CBF"""

def prediksi_cf(user_id, item_id, k=10):
    """Prediksi rating user-based dan CF."""
    penilai = user_item_matrix[item_id].dropna().drop(index=user_id, errors='ignore')
    if len(penilai) == 0:
        return None
    sim = user_sim_df.loc[user_id, penilai.index]
    sim = sim[sim > 0]
    if len(sim) == 0:
        return None
    top_k = sim.sort_values(ascending=False).head(k)
    pembilang = sum(top_k[v] * (user_item_matrix.loc[v, item_id] - user_means[v])
                     for v in top_k.index)
    penyebut = sum(abs(s) for s in top_k)
    return None if penyebut == 0 else user_means[user_id] + pembilang / penyebut


def rekomendasi_weighted_hybrid(user_id, top_n=5, alpha=0.6, beta=0.4, k=10):
    """
    WEIGHTED HYBRID untuk pelanggan lama:
      skor_akhir = alpha * skor_CF_ternormalisasi + beta * skor_CBF
    - skor_CF (hasil prediksi rating, skala ~1-5) dinormalisasi ke 0-1
      dengan dibagi 5, supaya sebanding dengan skor_CBF yang sudah 0-1.
    - Kalau CF tidak bisa memberi skor untuk suatu item (tidak ada
      tetangga yang pernah menilainya), sistem otomatis pakai CBF saja
      untuk item itu (alpha efektif jadi 0, beta jadi 1) -- ini bentuk
      graceful degradation, bukan error.
    Bobot default alpha=0.6, beta=0.4 mengikuti proporsi yang sama
    dengan modul hybrid PHP (`rekomendasi.php`) yang sudah berjalan di
    aplikasi, supaya konsisten satu sistem.
    """
    sudah_dipesan = user_item_matrix.loc[user_id].dropna().index
    kandidat = [i for i in user_item_matrix.columns if i not in sudah_dipesan]

    hasil = []
    for item_id in kandidat:
        skor_cbf = cbf_affinity(user_id, item_id)
        skor_cf_raw = prediksi_cf(user_id, item_id, k=k)

        if skor_cf_raw is not None:
            skor_cf_norm = max(0.0, min(1.0, skor_cf_raw / 5.0))
            skor_akhir = alpha * skor_cf_norm + beta * skor_cbf
            sumber = "CF+CBF"
        else:
            skor_akhir = skor_cbf
            sumber = "CBF (CF tidak tersedia utk item ini)"

        hasil.append((item_id, skor_akhir, sumber))

    hasil.sort(key=lambda x: x[1], reverse=True)
    hasil = hasil[:top_n]

    df_hasil = df_menu[df_menu['ID_Menu'].isin([i for i, _, _ in hasil])].copy()
    skor_map = {i: round(s, 3) for i, s, _ in hasil}
    sumber_map = {i: sb for i, _, sb in hasil}
    df_hasil['skor_hybrid'] = df_hasil['ID_Menu'].map(skor_map)
    df_hasil['sumber'] = df_hasil['ID_Menu'].map(sumber_map)
    df_hasil = df_hasil.sort_values('skor_hybrid', ascending=False)
    return df_hasil[['Nama_Menu', 'Kategori_Hidangan', 'Bahan_Baku',
                      'Rasa_Dominan', 'skor_hybrid', 'sumber']].reset_index(drop=True)

"""### 4.4 REKOMENDASI POPULER"""

def rekomendasi_populer(top_n=5):
    """
    Dipakai kalau pelanggan baru DAN belum sempat ditanya preferensinya
    sama sekali (mis. buru-buru). Murni dari rata-rata rating menu di
    seluruh riwayat transaksi -- tidak personal, tapi tetap lebih baik
    daripada tidak merekomendasikan apa-apa.
    """
    rata2 = (user_item_matrix.mean(axis=0)
             .sort_values(ascending=False).head(top_n))
    df_hasil = df_menu[df_menu['ID_Menu'].isin(rata2.index)].copy()
    df_hasil['skor_populer'] = df_hasil['ID_Menu'].map(rata2.round(2))
    return df_hasil.sort_values('skor_populer', ascending=False)[
        ['Nama_Menu', 'Kategori_Hidangan', 'Bahan_Baku', 'Rasa_Dominan', 'skor_populer']
    ].reset_index(drop=True)


def rekomendasi_dari_preferensi(kategori=None, bahan=None, rasa=None, top_n=5):
    """CBF murni dari preferensi yang diucapkan pelanggan baru (dari Tahap 1)."""
    bagian = [str(x).replace(' ', '_') for x in (kategori, bahan, rasa) if x]
    if not bagian:
        return pd.DataFrame()
    query_vec = tfidf.transform([' '.join(bagian)])
    from sklearn.metrics.pairwise import cosine_similarity as cs
    skor = cs(query_vec, tfidf_matrix).flatten()
    hasil = df_menu.copy()
    hasil['skor_kecocokan'] = skor.round(3)
    hasil = hasil.sort_values('skor_kecocokan', ascending=False).head(top_n)
    return hasil[['Nama_Menu', 'Kategori_Hidangan', 'Bahan_Baku',
                   'Rasa_Dominan', 'skor_kecocokan']].reset_index(drop=True)

"""### 4.5 FUNGSI UTAMA: SWITCHING HYBRID"""

def rekomendasi_hybrid(user_id=None, kategori=None, bahan=None, rasa=None,
                        top_n=5, alpha=0.6, beta=0.4):
    """
    Titik masuk tunggal yang dipanggil dari sisi aplikasi (mis. pelayan
    input di form pemesanan). Logika SWITCHING HYBRID ada persis di
    percabangan if/else di bawah ini:

      if pelanggan dikenali & punya riwayat transaksi:
          -> WEIGHTED HYBRID (CF + CBF)
      elif pelanggan baru TAPI preferensi rasa/bahan/kategori sudah
           didapat lewat dialog (Conversational Recommender):
          -> CBF murni dari preferensi tsb
      else (pelanggan baru & belum ada info apa pun):
          -> rekomendasi populer (jaring pengaman)
    """
    # --- STATUS PELANGGAN ---
    is_pelanggan_lama = (user_id is not None) and (user_id in user_item_matrix.index)

    if is_pelanggan_lama:
        print(f"[Switching Hybrid] '{user_id}' = PELANGGAN LAMA "
              f"({len(user_item_matrix.loc[user_id].dropna())} riwayat transaksi) "
              f"-> WEIGHTED HYBRID (CF + CBF, alpha={alpha}, beta={beta})")
        return rekomendasi_hybrid_lama_atau_kosong(user_id, top_n, alpha, beta)

    elif kategori or bahan or rasa:
        print(f"[Switching Hybrid] Pelanggan BARU (cold start), preferensi sudah "
              f"didapat lewat dialog pelayan (Conversational Recommender): "
              f"kategori={kategori}, bahan={bahan}, rasa={rasa} -> CBF murni")
        return rekomendasi_dari_preferensi(kategori, bahan, rasa, top_n)

    else:
        print("[Switching Hybrid] Pelanggan BARU (cold start), preferensi belum "
              "sempat ditanyakan -> fallback rekomendasi POPULER")
        return rekomendasi_populer(top_n)


def rekomendasi_hybrid_lama_atau_kosong(user_id, top_n, alpha, beta):
    hasil = rekomendasi_weighted_hybrid(user_id, top_n, alpha, beta)
    if hasil.empty:
        return rekomendasi_populer(top_n)
    return hasil

"""### 4.6 PENGUJIAN 3 SKENARIO"""

print("=== SKENARIO A: Pelanggan LAMA (punya riwayat transaksi) ===")
print(rekomendasi_hybrid(user_id='U001', top_n=5).to_string(index=False))
print()

print("=== SKENARIO B: Pelanggan BARU, sudah didialog pelayan ===")
print("(Pelayan bertanya: 'suka rasa apa dan bahan apa?' -> dijawab pedas & ayam)")
print(rekomendasi_hybrid(user_id='U_BARU_001', bahan='Ayam', rasa='Pedas', top_n=5)
      .to_string(index=False))
print()

print("=== SKENARIO C: Pelanggan BARU, belum sempat didialog ===")
print(rekomendasi_hybrid(user_id='U_BARU_002', top_n=5).to_string(index=False))
print()

"""### 4.7 SIMPAN ARTEFAK HYBRID UNTUK TAHAP BERIKUTNYA (mis. evaluasi / integrasi API)"""

with open('hybrid_artifacts.pkl', 'wb') as f:
    pickle.dump({
        'df_menu': df_menu,
        'tfidf_vectorizer': tfidf,
        'tfidf_matrix': tfidf_matrix,
        'cosine_sim_matrix': cos_sim,
        'user_item_matrix': user_item_matrix,
        'user_means': user_means,
        'user_similarity_matrix': user_sim_df,
        'alpha_default': 0.6,
        'beta_default': 0.4,
    }, f)

print("Artefak hybrid lengkap disimpan ke 'hybrid_artifacts.pkl'.")
print("Siap dipakai untuk tahap evaluasi (Precision@K/Recall@K/NDCG) atau")
print("langsung diekspos sebagai endpoint di app.py (Flask).")

"""# 5. Pengujian dan Evaluasi

### 5.1 MUAT DATA & TRAIN-TEST SPLIT (per pelanggan, kronologis)
"""

df_trans = pd.read_csv('data_transaksi_final.csv')
df_trans['Waktu_Transaksi'] = pd.to_datetime(
    df_trans['Waktu_Transaksi'], format='mixed', dayfirst=True
)
# agregasi (User_ID, ID_Menu) duplikat -> rata-rata rating, ambil transaksi terakhir
df_agg = (df_trans.groupby(['User_ID', 'ID_Menu'], as_index=False)
          .agg({'Rating_Pelanggan': 'mean', 'Waktu_Transaksi': 'max'}))

train_parts, test_parts = [], []
for uid, grp in df_agg.groupby('User_ID'):
    grp = grp.sort_values('Waktu_Transaksi')
    n_test = max(1, round(len(grp) * 0.2))       # 20% transaksi TERBARU -> test
    test_parts.append(grp.iloc[-n_test:])
    train_parts.append(grp.iloc[:-n_test])
df_train = pd.concat(train_parts).reset_index(drop=True)
df_test = pd.concat(test_parts).reset_index(drop=True)

print("=== 1. Train-Test Split ===")
print(f"Total data: {len(df_agg)} | Train: {len(df_train)} ({len(df_train)/len(df_agg):.0%}) "
      f"| Test: {len(df_test)} ({len(df_test)/len(df_agg):.0%})")
print(f"Pembagian per pelanggan, kronologis (transaksi TERBARU jadi data uji).")
print()

"""### 5.2 LATIH ULANG CF DARI TRAIN SAJA"""

uim = df_train.pivot_table(index='User_ID', columns='ID_Menu', values='Rating_Pelanggan')
user_means = uim.mean(axis=1)
uim_centered = uim.sub(user_means, axis=0).fillna(0)
user_sim = pd.DataFrame(cosine_similarity(uim_centered), index=uim.index, columns=uim.index)

with open('cbf_artifacts.pkl', 'rb') as f:
    cbf = pickle.load(f)
df_menu = cbf['df_menu']
cos_sim = cbf['cosine_sim_matrix']
id_to_idx = {mid: i for i, mid in enumerate(df_menu['ID_Menu'])}
all_items = list(df_menu['ID_Menu'])

print("=== 2. CF dilatih ulang dari data TRAIN saja ===")
print(f"User-Item matrix (train): {uim.shape[0]} user x {uim.shape[1]} menu")
print()


def prediksi_cf(user_id, item_id, k=10):
    if item_id not in uim.columns or user_id not in uim.index:
        return None
    penilai = uim[item_id].dropna().drop(index=user_id, errors='ignore')
    if len(penilai) == 0:
        return None
    sim = user_sim.loc[user_id, penilai.index]
    sim = sim[sim > 0]
    if len(sim) == 0:
        return None
    top_k = sim.sort_values(ascending=False).head(k)
    num = sum(top_k[v] * (uim.loc[v, item_id] - user_means[v]) for v in top_k.index)
    den = sum(abs(s) for s in top_k)
    return None if den == 0 else user_means[user_id] + num / den


def cbf_affinity(user_id, item_id):
    riwayat = uim.loc[user_id].dropna() if user_id in uim.index else pd.Series(dtype=float)
    if len(riwayat) == 0:
        return 0.0
    cand = id_to_idx[item_id]
    tot_s = sum(r * cos_sim[cand, id_to_idx[i]] for i, r in riwayat.items())
    tot_b = riwayat.sum()
    return tot_s / tot_b if tot_b > 0 else 0.0


def rmse(a, p):
    return float(np.sqrt(np.mean((np.array(a) - np.array(p)) ** 2)))


def mae(a, p):
    return float(np.mean(np.abs(np.array(a) - np.array(p))))

"""### 5.3 EVALUASI RMSE / MAE: baseline vs CF-only vs Hybrid"""

print("=== 3. Evaluasi RMSE & MAE (akurasi prediksi rating) ===")

# cache prediksi mentah per baris test, dipakai ulang di tahap tuning (hemat waktu)
cache = []
for _, row in df_test.iterrows():
    uid, iid, actual = row['User_ID'], row['ID_Menu'], row['Rating_Pelanggan']
    cache.append((actual, prediksi_cf(uid, iid), cbf_affinity(uid, iid), uid))

actual_all = [c[0] for c in cache]

# Baseline 1: selalu tebak rata-rata rating global
global_mean = df_train['Rating_Pelanggan'].mean()
pred_global = [global_mean] * len(cache)

# Baseline 2: selalu tebak rata-rata rating user itu sendiri
pred_usermean = [user_means.get(uid, global_mean) for _, _, _, uid in cache]

# CF-only (hanya baris yang berhasil diprediksi CF)
mask_cf = [c[1] is not None for c in cache]
actual_cf = [c[0] for c, m in zip(cache, mask_cf) if m]
pred_cf = [c[1] for c, m in zip(cache, mask_cf) if m]
gagal_cf = len(cache) - len(actual_cf)

# Hybrid (default alpha=0.6/beta=0.4, coverage 100% krn CBF selalu bisa jadi fallback)
def skor_hybrid(p_cf, s_cbf, alpha, beta):
    p_cf_norm = max(0.0, min(1.0, p_cf / 5)) if p_cf is not None else 0.0
    return (alpha * p_cf_norm + beta * s_cbf) * 4 + 1  # skala 0-1 -> 1-5

pred_hybrid_default = [skor_hybrid(c[1], c[2], 0.6, 0.4) for c in cache]

hasil_rmse = pd.DataFrame([
    {'Metode': 'Baseline: rata-rata global', 'RMSE': rmse(actual_all, pred_global),
     'MAE': mae(actual_all, pred_global), 'Cakupan_Test': '100%'},
    {'Metode': 'Baseline: rata-rata per user', 'RMSE': rmse(actual_all, pred_usermean),
     'MAE': mae(actual_all, pred_usermean), 'Cakupan_Test': '100%'},
    {'Metode': 'CF-only', 'RMSE': rmse(actual_cf, pred_cf), 'MAE': mae(actual_cf, pred_cf),
     'Cakupan_Test': f'{100*len(actual_cf)/len(cache):.1f}% ({gagal_cf} gagal diprediksi)'},
    {'Metode': 'Hybrid (alpha=0.6, beta=0.4)', 'RMSE': rmse(actual_all, pred_hybrid_default),
     'MAE': mae(actual_all, pred_hybrid_default), 'Cakupan_Test': '100%'},
])
print(hasil_rmse.to_string(index=False))
print()

"""### 5.4 TUNING BOBOT ALPHA/BETA (cari RMSE terendah)"""

print("=== 4. Tuning Bobot Weighted Hybrid (mencari alpha optimal) ===")
tuning = []
for alpha in np.arange(0.0, 1.01, 0.1):
    beta = round(1 - alpha, 2)
    pred = [skor_hybrid(c[1], c[2], alpha, beta) for c in cache]
    tuning.append({'alpha': round(alpha, 1), 'beta': beta,
                    'RMSE': rmse(actual_all, pred), 'MAE': mae(actual_all, pred)})
df_tuning = pd.DataFrame(tuning)
print(df_tuning.to_string(index=False))

alpha_terbaik = df_tuning.loc[df_tuning['RMSE'].idxmin()]
print(f"\n-> Bobot dengan RMSE terendah: alpha={alpha_terbaik['alpha']}, "
      f"beta={alpha_terbaik['beta']} (RMSE={alpha_terbaik['RMSE']:.4f})")
print("CATATAN: bobot 0.6/0.4 yang dipakai di modul PHP (rekomendasi.php) TERNYATA")
print("bukan yang RMSE-nya paling rendah di data ini -- pertimbangkan menyesuaikan")
print("bobot berdasarkan hasil tuning ini kalau ingin konsisten satu sistem.")
print()

ALPHA_OPTIMAL = float(alpha_terbaik['alpha'])
BETA_OPTIMAL = float(alpha_terbaik['beta'])

"""### 5.5 EVALUASI PRECISION@K / RECALL@K (akurasi top-N rekomendasi)"""

print("=== 5. Evaluasi Precision@K & Recall@K (akurasi ranking top-N) ===")

def topk_rekomendasi(user_id, K, alpha, beta):
    sudah = set(uim.loc[user_id].dropna().index) if user_id in uim.index else set()
    kandidat = [i for i in all_items if i not in sudah]
    skor = []
    for item in kandidat:
        p_cf = prediksi_cf(user_id, item)
        s_cbf = cbf_affinity(user_id, item)
        p_cf_norm = max(0.0, min(1.0, p_cf / 5)) if p_cf is not None else 0.0
        skor.append((item, alpha * p_cf_norm + beta * s_cbf))
    skor.sort(key=lambda x: x[1], reverse=True)
    return [i for i, _ in skor[:K]]

# item "relevan" = pernah dipesan lagi di test set dengan rating >= 4
relevan = (df_test[df_test['Rating_Pelanggan'] >= 4]
           .groupby('User_ID')['ID_Menu'].apply(set).to_dict())
eligible_users = [u for u, r in relevan.items() if len(r) > 0]
print(f"Pelanggan dgn minimal 1 menu relevan (rating>=4) di test set: {len(eligible_users)} dari {uim.shape[0]}")

rng = random.Random(RANDOM_SEED)
K = 5

def evaluasi_topk(alpha=None, beta=None, metode='hybrid'):
    precisions, recalls = [], []
    for uid in eligible_users:
        rel = relevan[uid]
        if metode == 'random':
            rekom = rng.sample(all_items, K)
        else:
            rekom = topk_rekomendasi(uid, K, alpha, beta)
        hit = len(set(rekom) & rel)
        precisions.append(hit / K)
        recalls.append(hit / min(len(rel), K))
    return float(np.mean(precisions)), float(np.mean(recalls))

hasil_topk = []
for label, alpha, beta, metode in [
    ('Baseline: rekomendasi acak', None, None, 'random'),
    ('CF-only', 1.0, 0.0, 'hybrid'),
    ('Hybrid (alpha=0.6, beta=0.4)', 0.6, 0.4, 'hybrid'),
    (f'Hybrid tuned (alpha={ALPHA_OPTIMAL}, beta={BETA_OPTIMAL})', ALPHA_OPTIMAL, BETA_OPTIMAL, 'hybrid'),
]:
    p, r = evaluasi_topk(alpha, beta, metode)
    hasil_topk.append({'Metode': label, f'Precision@{K}': round(p, 4), f'Recall@{K}': round(r, 4)})

df_topk = pd.DataFrame(hasil_topk)
print(df_topk.to_string(index=False))
print()

"""### 5.6 DIAGNOSTIK: apakah rating benar-benar berhubungan dgn fitur menu?"""

print("=== 6. Diagnostik: hubungan fitur menu (Kategori/Bahan/Rasa) dgn rating ===")
merged = df_trans.merge(df_menu, on='ID_Menu')
for kolom in ['Kategori_Hidangan', 'Bahan_Baku', 'Rasa_Dominan']:
    grup = [g['Rating_Pelanggan'].values for _, g in merged.groupby(kolom)]
    f_stat, p_val = stats.f_oneway(*grup)
    signifikan = "signifikan (p<0.05)" if p_val < 0.05 else "TIDAK signifikan (p>=0.05)"
    print(f"ANOVA rating vs {kolom:20s}: F={f_stat:6.3f}, p={p_val:.4f} -> {signifikan}")
print()
print("Interpretasi: kalau ketiga fitur ini TIDAK signifikan / signifikansinya sangat")
print("lemah, artinya pada dataset transaksi yang dipakai saat ini, rating pelanggan")
print("kemungkinan besar dibangkitkan independen dari fitur konten menu. Ini bukan")
print("kesalahan implementasi CF/CBF/Hybrid -- tapi karakteristik data sintetis yang")
print("dipakai. WAJIB disebutkan di BAB 5 (Keterbatasan Penelitian) kalau hasilnya")
print("memang begitu, supaya evaluasi ini kredibel saat sidang.")
print()

"""### 5.7 RINGKASAN HASIL EVALUASI"""

print("=== 7. Ringkasan Hasil Evaluasi ===")
print(hasil_rmse.to_string(index=False))
print()
print(df_topk.to_string(index=False))
print()
print(f"Bobot Weighted Hybrid yang direkomendasikan dari hasil tuning: "
      f"alpha={ALPHA_OPTIMAL}, beta={BETA_OPTIMAL}")

with open('hasil_evaluasi.pkl', 'wb') as f:
    pickle.dump({
        'rmse_mae': hasil_rmse,
        'tuning_alpha': df_tuning,
        'precision_recall': df_topk,
        'alpha_optimal': ALPHA_OPTIMAL,
        'beta_optimal': BETA_OPTIMAL,
    }, f)
print("\nSemua tabel hasil evaluasi disimpan ke 'hasil_evaluasi.pkl' untuk dipakai di BAB 4.")